<?php
/**
* Implement hook_install().
*
* Perform actions to set up the site for this profile.
*/
function stanford_sites_jumpstart_personal_install() {}

/**
 * Implements hook_uninstall().
 */
function stanford_sites_jumpstart_personal_uninstall() {}

/**
 * Implements hook_requirements().
 */
function stanford_sites_jumpstart_personal_requirements($phase) {
  $requirements = array();
  return $requirements;
}
